/*
 * Copyright 2018-2020 Todd Lang
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
using System.Collections.Generic;

namespace RiftDrive.Shared.Provider {
	internal sealed class NameProvider: INameProvider {

		private readonly IRandomProvider _random;

		public NameProvider(IRandomProvider random) {
			_random = random;
		}

		string INameProvider.CreateActorName() {
			return $"{GetFirstName()} {GetLastName()}";
		}

		private string GetFirstName() {
			var firstNames = new List<string>() {
				"Sarah",
				"Emily",
				"Emma",
				"Jessica",
				"Hannah",
				"Samantha",
				"Catherine",
				"Rachel",
				"Jade",
				"Amy",
				"Julia",
				"Laurence",
				"Audrey",
				"Camille",
				"Megan",
				"Madison",
				"Marie",
				"Gabrielle",
				"Ashley",
				"Taylor",
				"Kayla",
				"Maude",
				"Vanessa",
				"Laura",
				"Stephanie",
				"Sabrina",
				"Alexandra",
				"Laurie",
				"Chloe",
				"Olivia",
				"Rebecca",
				"Mélissa",
				"Lauren",
				"Émilie",
				"Morgan",
				"Andrea",
				"Jenna",
				"Frédérique",
				"Sydney",
				"Julie",
				"Caroline",
				"Chelsea",
				"Jennifer",
				"Justine",
				"Alyssa",
				"Elizabeth",
				"Charlotte",
				"Amanda",
				"Bianca",
				"Ànna",
				"Marianne",
				"Amélie",
				"Alicia",
				"Kate",
				"Myriam",
				"Roxanne",
				"Erika",
				"Victoria",
				"Sophie",
				"Mary",
				"Mia",
				"Rosalie",
				"Michelle",
				"Ariane",
				"Valérie",
				"Nicole",
				"Geneviève",
				"Vicky",
				"Alice",
				"Brittany",
				"Mackenzie",
				"Amber",
				"Karine",
				"Leah",
				"Brianna",
				"isabelle",
				"Isabel",
				"Émy",
				"Katie",
				"Kendra",
				"Claire",
				"Paige",
				"Haley",
				"Marie-Eve",
				"Florence",
				"Grace",
				"Jamie",
				"Mélanie",
				"Hailey",
				"Kim",
				"Kaitlyn",
				"Danielle",
				"Alexa",
				"Sara",
				"Annabelle",
				"Natalie",
				"Jordan",
				"Claudia",
				"Marie-Pier",
				"Alex",
				"Nathan",
				"Simon",
				"William",
				"David",
				"Nicolas",
				"Samuel",
				"Gabriel",
				"Kevin",
				"Charles",
				"Antoine",
				"Jordan",
				"Eric",
				"Alexandre",
				"Vincent",
				"Adam",
				"Brandon",
				"Ryan",
				"Michael",
				"Ben",
				"Etienne",
				"John",
				"Ethan",
				"Matthew",
				"Justin",
				"Maxime",
				"Anthony",
				"Kyle",
				"Andrew",
				"Owen",
				"James",
				"Josh",
				"Mathieu",
				"Liam",
				"Philippe",
				"Sam",
				"Austin",
				"Jeremy",
				"Daniel",
				"Nick",
				"Matt",
				"Tony",
				"Jason",
				"Chris",
				"Max",
				"Nicholas",
				"Dave",
				"Cédric",
				"Aidan",
				"Julien",
				"Mark",
				"Luke",
				"Olivier",
				"Jack",
				"Raphael",
				"Jake",
				"Guillaume",
				"Tyler",
				"Christian",
				"Evan",
				"Francis",
				"Jacob",
				"Paul",
				"Thomas",
				"Colton",
				"Alexis",
				"Antonio",
				"Bill",
				"Brad",
				"Zachary",
				"Cameron",
				"Will",
				"Joshua",
				"Frederic",
				"George",
				"Alexander",
				"Joseph",
				"Bobby",
				"Christophe",
				"Carter",
				"Aaron",
				"Riley",
				"Isaak",
				"Carl",
				"Jérôme",
				"Jean",
				"Jean-Sébastien",
				"Walid",
				"Joey",
				"Logan",
				"Ty",
				"Jesse",
				"Lucas",
				"Ken",
				"Jules",
				"Sonny",
				"Jimmy",
				"Felix",
				"Pascal",
				"Emile"
			};

			return firstNames[_random.Next( firstNames.Count )];
		}

		private string GetLastName() {
			var lastNames = new List<string>() {
				"Smith",
				"Brown",
				"Tremblay",
				"Martin",
				"Roy",
				"Wilson",
				"Macdonald",
				"Gagnon",
				"Johnson",
				"Taylor",
				"Cote",
				"Campbell",
				"Anderson",
				"Leblanc",
				"Lee",
				"Jones",
				"White",
				"Williams",
				"Miller",
				"Thompson",
				"Gauthier",
				"Young",
				"Van",
				"Morin",
				"Bouchard",
				"Scott",
				"Stewart",
				"Belanger",
				"Reid",
				"Pelletier",
				"Moore",
				"Lavoie",
				"King",
				"Robinson",
				"Levesque",
				"Murphy",
				"Fortin",
				"Gagne",
				"Wong",
				"Clark",
				"Johnston",
				"Clarke",
				"Ross",
				"Walker",
				"Thomas",
				"Boucher",
				"Landry",
				"Kelly",
				"Bergeron",
				"Davis",
				"Mitchell",
				"Murray",
				"Poirier",
				"Mcdonald",
				"Richard",
				"Wright",
				"Girard",
				"Lewis",
				"Baker",
				"Roberts",
				"Simard",
				"Graham",
				"Caron",
				"Harris",
				"Jackson",
				"Green",
				"Beaulieu",
				"Fraser",
				"Fournier",
				"Kennedy",
				"Hall",
				"Hill",
				"Chan",
				"Wood",
				"Lapointe",
				"Ouellet",
				"Bell",
				"Dube",
				"Allen",
				"Adams",
				"Cloutier",
				"Bennett",
				"Lefebvre",
				"Watson",
				"Robertson",
				"Walsh",
				"Collins",
				"Evans",
				"Hebert",
				"Hamilton",
				"Cameron",
				"Desjardins",
				"Russell",
				"Nadeau",
				"Cook",
				"Michaud",
				"Morrison",
				"Singh",
				"Grant",
				"Parsons"
			};

			return lastNames[_random.Next( lastNames.Count )];
		}

		string INameProvider.CreateMothershipName() {
			if (_random.Flip()) {
				return $"{GetSubject()}{GetAction()}";
			} else {
				return $"{GetObject()} of {GetSubject()}";
			}
		}

		private string GetObject() {
			var words = new List<string>() {
				"Pillar",
				"Column",
				"Sword",
				"Shield",
				"Cloak",
				"Armour",
				"Arrow",
				"Spear",
				"Axe",
				"Fortress",
				"Guardian",
				"Protector",
				"Destroyer"
			};

			return words[_random.Next( words.Count )];
		}

		private string GetSubject() {
			var prefixes = new List<string>() {
				"Spring",
				"Summer",
				"Autumn",
				"Winter",
				"Dawn",
				"Void",
				"Earth",
				"Fire",
				"Wind",
				"Star",
				"Water",
				"Glory",
				"Dusk",
				"Cloud",
				"Nova",
				"Dark",
				"Light",
				"Dust",
				"Hope",
				"Fury",
				"Galaxy",
				"Quantum",
				"Shield",
				"Ether",
				"Shadow"
			};

			return prefixes[_random.Next( prefixes.Count )];
		}

		private string GetAction() {
			var suffixes = new List<string>() {
				"strider",
				"striker",
				"walker",
				"shatterer",
				"builder",
				"changer",
				"bringer",
				"taker",
				"eater",
				"stealer",
				"stopper",
				"bearer",
				"cleaver",
				"treader"
			};

			return suffixes[_random.Next( suffixes.Count )];
		}
	}
}
